from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []

# add LittlevGL2RTT common include
inc = inc + [cwd]

# add LittlevGL2RTT basic code
src = Glob('*.c')

group = DefineGroup('LittlevGL2RTT_Demo', src, depend = ['LITTLEVGL2RTT_USING_DEMO'], CPPPATH = inc)

Return('group')
